### ISSUE TITLE
Project can't run

### ISSUE THREAD

**Issue by isfaaghyth** [ojaynico/kotlin-js-react-gradle#1]
Hi, your project is great! but unfortunately, I can't run it by `./gradlew -continous run`.

stacktrace:
`java.lang.IllegalArgumentException: The specified settings file '/Users/isfha/kotlin-js/kotlin-js-react-gradle/ontinous' does not exist.
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.validateIsFileAndExists(StartParamsValidatingActionExecuter.java:66)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:54)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)`

**Comment by ojaynico** [comment]
@isfaaghyth 
The word continuous in the gradle command has a typo in it. It is supposed to be `continuous` not `continous`.
So the final command is `./gradlew -continuous run`

I am going to correct this and update the repo. Thanks.

**Comment by isfaaghyth** [comment]
I see... it's running now, thanks!
